# Generated by Django 5.2.8 on 2025-11-11 04:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('terms', models.TextField(verbose_name='Términos y Condiciones')),
                ('duration_days', models.PositiveIntegerField(help_text='Duración total en días (ej. 365 para 1 año, 730 para 2 años)', verbose_name='Duración (días)')),
            ],
            options={
                'verbose_name': 'Plantilla de Garantía',
                'verbose_name_plural': 'Plantillas de Garantía',
            },
        ),
        migrations.CreateModel(
            name='WarrantyProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la Empresa')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Proveedor de Garantía',
                'verbose_name_plural': 'Proveedores de Garantía',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='URL de Imagen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoría')),
                ('warranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.warranty', verbose_name='Plantilla de Garantía')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ActivatedWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, verbose_name='Fecha de Vencimiento')),
                ('warranty_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Código de Garantía')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_warranties', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Producto Comprado')),
                ('warranty_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.warranty', verbose_name='Plantilla Aplicada')),
            ],
            options={
                'verbose_name': 'Garantía Activada',
                'verbose_name_plural': 'Garantías Activadas',
            },
        ),
        migrations.AddField(
            model_name='warranty',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranties', to='products.warrantyprovider', verbose_name='Proveedor'),
        ),
    ]


