# Generated by Django 5.2.8 on 2025-11-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_product_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivatedWarranty',
        ),
    ]


