# Generated by Django 5.2 on 2025-04-08 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_permissions_role_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='nombre',
            new_name='country',
        ),
        migrations.AddField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
