# Generated by Django 5.2.8 on 2025-11-11 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_activatedwarranty'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total',
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completada'), ('FAILED', 'Fallida')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ActivatedWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_warranties', to='sales.sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activated_warranties', to=settings.AUTH_USER_MODEL)),
                ('warranty_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.warranty')),
            ],
        ),
        migrations.CreateModel(
            name='SaleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_details', to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sales.sale')),
            ],
        ),
    ]


