# Generated by Django 5.1.7 on 2025-04-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_minimo',
            field=models.IntegerField(default=5),
        ),
    ]
